server:
  port: 8050

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.65:8848

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: data-client
          uri: lb://data-client
          predicates:
          - Path= /person/**


# Actuator
management:
  health:
    status:
      http-mapping:
        DOWN: 200
        OUT_OF_SERVICE: 200
        FATAL: 200
        UNKNOWN: 200
    # 暂未用到ES 关闭其健康检查
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: *
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always
#
#alibaba:
#  cloud:
#    access-key: 2020
#    secret-key: test


