
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/hotel;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: com.mysql.jdbc.Driver
    username: sa
    password:
    sql-script-encoding: utf-8     #需设置
#    initialize: true

